services:
  startechnology:
    image: eclipse-temurin:17-jre-jammy
    container_name: startechnology
    working_dir: /data
    command: ["/bin/bash", "-lc", "chmod +x ./run.sh && ./run.sh"]
    volumes:
      - /home/crafter32/StarT-Eta-2-Hf-1-Server-Files:/data
    ports:
      - "25565:25565"      # Minecraft-Port
      # - "25575:25575"    # RCON
    environment:
      - TZ=Europe/Vienna
      - EULA=TRUE
    tty: true
    stdin_open: true
    restart: unless-stopped
    stop_grace_period: 120s
    mem_limit: 12g
    dns:
      - 192.168.178.1
      - 1.1.1.1
    stop_signal: SIGINT